### ISSUE TITLE
Fails at loading gallery

### ISSUE THREAD

**Issue by DUOLabs333** [geraldwuhoo/omgur#3]
I tried loading `https://imgur.com/gallery/dkGFq4G` with omgur, but fails with `http: panic serving 127.0.0.1:37098: interface conversion: interface {} is nil, not []interface {}
goroutine 98 [running]:`

**Comment by geraldwuhoo** [comment]
I think I have found the issue. Imgur galleries aren't necessarily albums. Even most single-image Imgur galleries I tested were still album structures, so I didn't realize this was a possibility.

Example:
```
$ curl --location --request GET 'https://api.imgur.com/3/gallery/pVgjT8j' --header 'Authorization: Client-ID 546c25a59c58ad7' 2> /dev/null | jq '.data.is_album'
true

$ curl --location --request GET 'https://api.imgur.com/3/gallery/dkGFq4G' --header 'Authorization: Client-ID 546c25a59c58ad7' 2> /dev/null | jq '.data.is_album'
false
```
(both of these are single-image galleries)

I will have a patch out to address this shortly. Thanks for bringing my attention to this.

**Comment by geraldwuhoo** [comment]
This has been fixed with [release v0.1.1](https://gitlab.com/98WuG/omgur/-/releases/v0.1.1).

**Comment by DUOLabs333** [comment]
It works, but for some reason, is much slower to load than the rest of the URLs.

**Comment by geraldwuhoo** [comment]
That is interesting. It does make one additional API call vs the rest of the URLs to determine album vs image, but otherwise follows the same codepaths (e.g. uses the same Album parser for albums, and the same Image parser for images). This means it should also use the same Redis cache if applicable. I don't particularly think that one additional API call would cause significant slowdown, especially compared to the actual bandwidth to load images/videos.

Testing with a fresh (empty) Redis cache and a clean browser (to rule out browser cache), the test URL you gave `gallery/dkGFq4G` loads nearly instantaneously for me.

**Comment by DUOLabs333** [comment]
Hmm, I'll try today (I set my browser to clear history every restart).

**Comment by DUOLabs333** [comment]
No, still slow.

**Comment by DUOLabs333** [comment]
To be fair, it's not that slow, around ~3 s, rather than <1 usually.

**Comment by DUOLabs333** [comment]
It seems that the slowdown is with the loading itself, as trying to load the MP4 directly is similarly slow.
